### ISSUE TITLE
Add support for local LLM

### ISSUE THREAD

**Issue by nicobrenner** [leapingio/leaping#3]
It would be nice to be able to choose a local model instead of having to use OpenAI's GPT

Checking out the code, it looks like `ollama-python` (https://github.com/ollama/ollama-python) could be relatively simple to add as an option inside the `GPT` class (https://github.com/leapingio/leaping/blob/main/pytest-leaping/src/leaping_gpt.py)

Below is a sample snippet from `ollama-python`'s `README`:

```python3
import ollama
response = ollama.chat(model='llama2', messages=[
  {
    'role': 'user',
    'content': 'Why is the sky blue?',
  },
])
print(response['message']['content'])
```

And here's the same as above, but doing streaming:

```python
import ollama

stream = ollama.chat(
    model='llama2',
    messages=[{'role': 'user', 'content': 'Why is the sky blue?'}],
    stream=True,
)

for chunk in stream:
  print(chunk['message']['content'], end='', flush=True)
```

**Comment by kvptkr** [comment]
That's a great shout - we just added the ability to bring your own models here - https://github.com/leapingio/leaping/pull/4. We didn't experience the best results with ollama2 when we tried it out, so I think we're going to do some additional work there! Thanks for the feedback + feature request, we love that

**Comment by nicobrenner** [comment]
Thank you so much for the super quick PR and feature add 😆
